### ISSUE TITLE
An error happens when I used libquantum.CINT.PP200M as a simulation trace. 

### ISSUE THREAD

**Issue by dentionY** [mazalves/OrCS#1]
I have read your new paper 

> 《[Machine Learning Migration for Efficient Near-Data Processing](https://web.inf.ufpr.br/mazalves/wp-content/uploads/sites/13/2021/04/PDP_2021_1.pdf)》

and I was interested in rebuilding it on my computer. Then I found your new simulation tool **OrCS** in GitHub when I used the website given in the paper.

I built OrCS in my Ubuntu-18.04.6 with steps provided on _https://github.com/mazalves/OrCS_ three days ago. However, an unanticipated error occurred when I tested OrCS with  [**libquantum.CINT.PP200M**](https://drive.google.com/drive/folders/1wJIxye5Cm4cRu3pTYrKkWfPF94_9h5uN) as a simulation trace. 

The details of the error are as follows:
`MEMORY_CONTROLLER_T::set_latency_burst = 20`
`terminate called after throwing an instance of 'libconfig::SettingNotFoundException'`
`    what():  SettingNotFoundException`
`Aborted (core dumped)`

I tried to solve the problem. The output might tell me a variant has no settings, which I confirmed in [**libconfig manual**.](https://usermanual.wiki/Document/libconfigmanual.2005283088/html) However, I found “`MEMORY_CONTROLLER_T::set_latency_burst` ” has been defined in _main_memory/memory_controller.cpp_. 

Related packages and compilers are _libconfig-1.4.9, zlib-1.2.8_ and _gcc-9, g++-9_, respectively.

I really look forward to your generous help. Thank you very much!

**Comment by sairosantos** [comment]
Hello, dentionY.

This is likely happening due to an outdated configuration file, my apologies. When using the sandy_bridge.cfg file, as is suggested in our guide for using the simulator, that issue comes up indeed. Please try to run the simulation trace with the configuration file skylakeServer.cfg, which can be found in the configuration_files folder. Thank you for pointing out this issue, we'll update the guide and the configuration files as soon as possible.
